export const queryKeys = {
  auth: {
    me: ['auth', 'me'] as const,
    departments: ['auth', 'departments'] as const,
    roles: ['auth', 'roles'] as const,
    designations: ['auth', 'designations'] as const,
  },
  prs: {
    all: ['prs'] as const,
    lists: () => [...queryKeys.prs.all, 'list'] as const,
    list: (page?: number, limit?: number) => ['prs', page, limit] as const,
    detail: (id: number | string) => ['pr', id] as const,
    dashboard: () => [...queryKeys.prs.all, 'dashboard'] as const,
    formsDashboard: () => ['prs', 'forms_dashboard'] as const,
  },
  budgets: {
    all: ['budgets'] as const,
    files: () => ['budgetFiles'] as const,
    overview: () => ['budget-overview'] as const,
    detail: (id: number | string) => ['budget_detail', id] as const,
    admin: (searchTerm?: string, deptFilter?: string, fyFilter?: string) => ['admin_budgets', searchTerm, deptFilter, fyFilter] as const,
    categories: ['budget_categories'] as const,
    financialYears: ['budget_financial_years'] as const,
    procurementMethods: ['procurementMethods'] as const,
    permanent: (deptId?: number | string, fyId?: number | string) => ['permanentBudgets', deptId, fyId] as const,
  },
  assets: {
    all: ['assets'] as const,
    list: (
      page?: number,
      limit?: number,
      searchTerm?: string,
      filterYear?: string,
      filterCategory?: string,
      filterCondition?: string,
      filterStatus?: string,
      filterFundSource?: string,
      filterDept?: string
    ) => ['assets', page, limit, searchTerm, filterYear, filterCategory, filterCondition, filterStatus, filterFundSource, filterDept] as const,
    detailList: ['assets', 'detail_list'] as const,
    detail: (id: number | string) => ['asset', id] as const,
    public: (tag: string) => ['asset-public', tag] as const,
    dashboard: () => [...queryKeys.assets.all, 'dashboard'] as const,
  },
  inventory: {
    deliveries: ['deliveries'] as const,
    delivery: (id: number | string) => ['delivery', id] as const,
    discrepancies: ['discrepancies'] as const,
  },
  admin: {
    users: ['admin_users'] as const,
    pendingUsers: ['admin_pending_users'] as const,
    roles: ['admin_roles'] as const,
    depts: ['admin_depts'] as const,
    departments: ['admin_departments'] as const,
    settings: ['admin_settings'] as const,
    workflows: ['admin_workflows'] as const,
    categories: ['admin_categories'] as const,
    phases: ['admin_phases'] as const,
    procs: ['admin_procs'] as const,
    usersList: ['admin_users_list'] as const,
    financialYears: ['admin_financial_years'] as const,
    aaWorkflows: ['admin_aa_workflows'] as const,
    sourceOfFunds: ['admin_source_of_funds'] as const,
  },
  users: {
    deptFaculty: ['departmentFaculty'] as const,
    directorNomination: ['all_users_for_director_nomination'] as const,
    consultation: ['all_users_for_consultation'] as const,
    allFaculties: ['all_faculties'] as const,
    allUsers: ['all_users'] as const,
    rolloverCandidates: ['rollover_candidates'] as const,
  }
};
