"""add_tender_scheduling_done_to_prs

Revision ID: ef00378a2363
Revises: a1b2c3d4e5f6
Create Date: 2026-06-12 06:26:16.933513

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ef00378a2363'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requests', sa.Column('tender_scheduling_done', sa.Boolean(), nullable=True))
    op.execute("UPDATE purchase_requests SET tender_scheduling_done = FALSE")
    op.alter_column('purchase_requests', 'tender_scheduling_done', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_requests', 'tender_scheduling_done')
    # ### end Alembic commands ###
